[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://zpbhwjnuqiomuufscvho.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwYmh3am51cWlvbXV1ZnNjdmhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNjkxNDUsImV4cCI6MjA3NTY0NTE0NX0.S1zwrdxL6L9gzGIORwMk00CVNM8_tg5EnLMGwqsWmks"
